name: Deplo To Github Pages

on:
  # 允许手动push触发
  push:
    branches:
      - main
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy # api中的event_type就是这个

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v2

      - name: 安装node环境
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      - name: 安装pnpm
        run: |
          export TZ='Asia/Shanghai'
          npm install pnpm@7.9.5 -g

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          pnpm install --prod

      - name: 拉取语雀/Notion的文章
        env:
          # 语雀相关环境变量
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          # Notion相关环境变量
					# NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          # NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # 图床相关环境变量，以腾讯云COS为例
          # COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          # COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          # COS_IMAGE_BUCKET: ${{ secrets.COS_IMAGE_BUCKET }}
          # COS_IMAGE_REGION: ${{ secrets.COS_IMAGE_REGION }}
        run: |
          pnpm sync # 对应package.json中的script.sync

      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "JasonMa0012"
          git config --global user.email "1312119064@qq.com"

      - name: 提交yuque拉取的文章到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "更新文档" -a

      - name: 推送文章到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 生成静态文件
        run: |
          pnpm build # 对应package.json中的script.build

      - name: 部署到Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token和personal_token适用于推送到当前仓库
          # 也就是你的Github Pages仓库（xxxx/xxxx.github.io）
          # 一般都不直接在Github Pages仓库开发，所以推荐使用deploy_key
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # deploy_key可以推送到别的仓库, SSH_PRIVATE_KEY 为自己电脑的ssh私钥
          # deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: docs/.vitepress/dist
          # external_repository: xxxx/xxxx.github.io
          # publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
